services:
  
  # NGINX API Gateway
  nginx:
    image: nginx:alpine-slim
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

  # Inventory Service
  inventory-service:
    image: ghcr.io/marekvonrogall/equity/inventory-service:latest
    container_name: inventory-service

  # Float Service
  float-service:
    image: ghcr.io/marekvonrogall/equity/float-service:latest
    container_name: float-service
